### ISSUE TITLE
Idempotency issues 

### ISSUE THREAD

**Issue by ericsysmin** [ericsysmin/community.zabbix#1]
@dj-wasabi When writing the collection tests I ran into this on Debian, Ubuntu was fine. Any idea on what you'd prefer I do on these tasks?

https://github.com/ericsysmin/community.zabbix/runs/653713392?check_suite_focus=true

```
ERROR: Idempotence test failed because of the following tasks:
An error occurred during the test sequence action: 'idempotence'. Cleaning up.
* [instance] => zabbix_agent : Debian | Remove unecessary zabbix repositories
* [instance] => zabbix_agent : Debian | Installing deb-src repository Debian
* [instance] => zabbix_agent : Debian | Installing deb repository Debian
```

**Comment by dj-wasabi** [comment]
Hi @ericsysmin 

It seems to be related to this value in `default/main.yml`:

`zabbix_agent_src_reinstall: True`

You can override it in the `molecule.yml` by setting it to `false`
